name: INTERX Build & Release

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  setup:
    name: Repo Setup
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
          - name: Install cosign
            uses: sigstore/cosign-installer@v2.1.0
            with:
              cosign-release: 'v1.6.0'
          - name: Checkout repository
            uses: actions/checkout@v3.0.0
          - name: Verify repo content
            run: |
              echo "(current dir): $PWD" && ls -l
  build:
    name: Repo Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [setup]
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
      volumes:
        - /home/runner/work/interx/interx:/host
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
              echo "HOME: $HOME"
              echo "ENVS: $(env)"
          - name: Testing INTERX
            working-directory: /home/runner/work/interx/interx
            run: |
              echo "(current dir): $PWD" && ls -l
              echo "(current /host):" && ls -l /host
              make install
              interxd version
              ls -l
          - name: Publishing INTERX binaries
            working-directory: ${{ env.HOME }}
            run: |
              make publish
              ls -l





