name: INTERX Build & Release

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  main:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
              echo "HOME: $HOME"
              echo "ENVS: $(env)"
          - name: Testing INTERX
            working-directory: /github/workspace
            run: |
              ls -l || cd / && ls -l || cd /github/workspace && ls -l 
              make install
              interxd version
              ls -l
          - name: Publishing INTERX binaries
            working-directory: /github/workspace
            run: |
              make publish
              ls -l





