name: Makefile CI

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  main:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
          - name: Testing INTERX
            run: |
              make install
              interxd version
              ls
          - name: Publishing INTERX binaries
            run: |
              make publish
              ls





