name: INTERX Build & Release

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
          - name: Checkout repository
            uses: actions/checkout@v3.0.0
          - name: Install cosign
            uses: sigstore/cosign-installer@v2.1.0
            with:
              cosign-release: 'v1.6.0'
  build:
    runs-on: ubuntu-20.04
    needs: [setup]
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
      volumes:
        - /home/runner/work/interx/interx:/github/workspace3
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
              echo "HOME: $HOME"
              echo "ENVS: $(env)"
          - name: Testing INTERX
            working-directory: ${{ github.workspace }}
            run: |
              echo "(current dir): $PWD" && ls -l
              echo "(/github/workspace3):" && ls -l /github/workspace3
              echo "(GITHUB_WORKSPACE): $GITHUB_WORKSPACE" && ls -l $GITHUB_WORKSPACE
              make install
              interxd version
              ls -l
          - name: Publishing INTERX binaries
            working-directory: ${{ env.HOME }}
            run: |
              make publish
              ls -l





