name: INTERX Build & Release

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
              echo "HOME: $HOME"
              echo "ENVS: $(env)"
          - name: Testing INTERX
            working-directory: ${{ env.RUNNER_WORKSPACE }}
            run: |
              ls -l || echo "NOT FOUND (current dir): $PWD"
              ls -l $GITHUB_WORKSPACE || echo "NOT FOUND (GITHUB_WORKSPACE): $GITHUB_WORKSPACE"
              ls -l $HOME || echo "NOT FOUND (HOME): $HOME"
              ls -l /github/home || echo "NOT FOUND: /github"
              ls -l /github/workflow || echo "NOT FOUND: /github/workflow"
              ls -l / || echo "NOT FOUND (/): /"
              ls -l /tmp || echo "NOT FOUND (/tmp): /tmp"
              ls -l $GITHUB_ENV || echo "NOT FOUND (GITHUB_ENV): $GITHUB_ENV"
              ls -l $GITHUB_PATH || echo "NOT FOUND (GITHUB_PATH): $GITHUB_PATH"
              ls -l $RUNNER_TOOL_CACHE || echo "NOT FOUND (RUNNER_TOOL_CACHE): $RUNNER_TOOL_CACHE"
              ls -l $RUNNER_WORKSPACE || echo "NOT FOUND (RUNNER_WORKSPACE): $RUNNER_WORKSPACE"
              ls -l $GITHUB_STEP_SUMMARY || echo "NOT FOUND (GITHUB_STEP_SUMMARY): $GITHUB_STEP_SUMMARY"
              make install
              interxd version
              ls -l
          - name: Publishing INTERX binaries
            working-directory: ${{ env.HOME }}
            run: |
              make publish
              ls -l





