name: INTERX Build & Release

on:
  push:
    branches: [ master, dev, v* ]
  pull_request:
    branches: [ master, dev, v* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
      volumes:
        - /home/runner/work/interx/interx:/github/workspace3
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
          - name: Checking dependency versions
            run: |
              . /etc/profile && echo "Utils Version: $(utilsVersion)"
              go version
              CDHelper version
              flutter --version
              dart --version
              echo "HOME: $HOME"
              echo "ENVS: $(env)"
          - name: Testing INTERX
            working-directory: /home/runner/work/interx/interx
            run: |
              echo "(current dir): $PWD" && ls -l
              echo "(/github/workspace3):" && ls -l /github/workspace3
              echo "(GITHUB_WORKSPACE): $GITHUB_WORKSPACE" && ls -l $GITHUB_WORKSPACE
              echo "(/__w): $PWD" && ls -l /__w
              echo "(/__w/interx): $PWD" && ls -l /__w/interx
              ls -l /github/home || echo "NOT FOUND: /github"
              ls -l /github/workflow || echo "NOT FOUND: /github/workflow"
              ls -l /tmp || echo "NOT FOUND (/tmp): /tmp"
              ls -l $GITHUB_ENV || echo "NOT FOUND (GITHUB_ENV): $GITHUB_ENV"
              ls -l $GITHUB_PATH || echo "NOT FOUND (GITHUB_PATH): $GITHUB_PATH"
              ls -l $RUNNER_TOOL_CACHE || echo "NOT FOUND (RUNNER_TOOL_CACHE): $RUNNER_TOOL_CACHE"
              ls -l $RUNNER_WORKSPACE || echo "NOT FOUND (RUNNER_WORKSPACE): $RUNNER_WORKSPACE"
              ls -l $GITHUB_STEP_SUMMARY || echo "NOT FOUND (GITHUB_STEP_SUMMARY): $GITHUB_STEP_SUMMARY"
              ls -l $RUNNER_WORKSPACE/interx || echo "NOT FOUND (RUNNER_WORKSPACE/interx): $RUNNER_WORKSPACE/interx"
              make install
              interxd version
              ls -l
          - name: Publishing INTERX binaries
            working-directory: ${{ env.HOME }}
            run: |
              make publish
              ls -l





