name: v*.*.* -PR-> master

on:
  pull_request:
    branches: [ latest ]
    types: [ opened ]

# git ls-remote <URL> | head -1 | sed "s/HEAD//"
jobs:
  # isolate signing & repo cloning from docker image
  auto-pr:
    name: Automated Master Branch PR
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
          - name: Extract branch name on pull request
            env:
              REF_BRANCH: ${{ github.event.pull_request.head.ref }}
              BASE_REF_BRANCH: ${{ github.base_ref }}
            shell: bash
            run: |
              echo "SOURCE_BRANCH=$(echo ${{ env.REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
              echo "DESTINATION_BRANCH=$(echo ${{ env.BASE_REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo "Source branch: ${{ env.SOURCE_BRANCH }}"
              echo "Destination branch: ${{ env.DESTINATION_BRANCH }}"
              echo "Event name: ${{ github.event_name }}"
          # ref.: https://github.com/actions/checkout, v3.0.0
          - name: Checkout repository
            uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
            with:
              ref: ${{ env.SOURCE_BRANCH }}
          - name: Create PR from a version branch to master after version branch merge
            if: |
              env.DESTINATION_BRANCH == 'latest' &&
              ( startsWith(env.SOURCE_BRANCH, 'v') && contains(env.SOURCE_BRANCH, '.') )
            uses: repo-sync/pull-request@5ba2c80b97c87b9174c1548141b7acd80f6376e1
            with:
              github_token: ${{ secrets.REPO_ACCESS }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              destination_branch: 'master'
              pr_title: "GithubActions ${{ env.SOURCE_BRANCH }} -> master" 
              pr_label: "kira-automation"
              pr_assignee: "asmodat"
              pr_allow_empty: true