name: Reject PRs to master, dev & latest branches NOT originating from version branches

on:
  pull_request:
    branches: [ master, dev, latest ]

jobs:
  # isolate signing & repo cloning from docker image
  setup:
    name: Build Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    env:
      REF_BRANCH: ${{ github.event.pull_request.head.ref }}
      BASE_REF_BRANCH: ${{ github.base_ref }}
    steps:
          # Branch name is also a version of the release
          # ref: https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
          - name: Extract branch name on pull request
            shell: bash
            run: |
              echo "SOURCE_BRANCH=$(echo ${{ env.REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
              echo "DESTINATION_BRANCH=$(echo ${{ env.BASE_REF_BRANCH }} | tr / -)" >> $GITHUB_ENV
          - name: Print debug data before publishing
            run: |
              echo "Source branch name: ${{ env.SOURCE_BRANCH }}"
              echo "Destination branch name: ${{ env.DESTINATION_BRANCH }}"
          - name: Reject on error
            # ref.: https://github.com/andrewslotin/rummelsnuff, v1.1.0
            uses: andrewslotin/rummelsnuff@a0c9c1929f44eefff922aced1ee4dd64eddf12d6
            if: |
              !contains(env.SOURCE_BRANCH, 'v') &&
              !contains(env.SOURCE_BRANCH, '.')
            with:
              spam_label: "Invalid Target"
              close_spam_prs: "yes"
              access_token: ${{ secrets.GITHUB_TOKEN }} 